### ISSUE TITLE
Pre- or posttrial significance?

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gamma-cat#106]
Which one do we usual quote in gamma-cat?

Noted this, as the following one uses the pre-trial significance:

https://github.com/gammapy/gamma-cat/blob/master/input/data/2013/2013ApJ...764...38A/tev-000001.yaml

**Comment by cdeil** [comment]
I always put pre-trial significance.

(Post-trial significance is a scam.)

I'll keep this issue open until this is mentioned in the gamma-cat docs.

**Comment by GernotMaier** [comment]
OK - I actually think that pre-trial significance is a useless numbers, without knowing the number of  trials.

**Comment by cdeil** [comment]
The number of trials is only known if everything is fixed before observing (target, exposure time, cuts, background estimation, energy range, assumed spectrum, ...). I'm not aware of a single TeV measurement where that is the case.

Probably doesn't make sense to argue that one over Github ...

Should we add a `significance_post_trial` key (or something shorter if you have an idea) in the schema so that we have a place to put this number if it's given in the paper?

**Comment by GernotMaier** [comment]
significance_post_trial is good - better than having an abbreviation which is not clear.

**Comment by cdeil** [comment]
I've improved the schema files quite a bit, adding descriptions to most fields.
And I've added `significance_post_trial` in 0aeac1e (not used by any dataset at the moment).
