### ISSUE TITLE
Crab Nebula source description (tev-000025)

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gamma-cat#138]
https://github.com/gammapy/gamma-cat/blob/master/input/sources/tev-000025.yaml

I suggest to change the 'discoverer' from HESS to Whipple!! 
 
But here is my question : why are there two different TeVCat IDs and Names?

**Comment by cdeil** [comment]
> I suggest to change the 'discoverer' from HESS to Whipple!!

Please do!

Note: Such simple "typos" can be fixed by a commit or PR just via the Github web user interface, going to the file and clicking the pencil symbol to edit in the upper right. The question whether to go through a PR or not is whether you want review. If it's a simple change that doesn't need discussion, you can commit directly to master.

> But here is my question : why are there two different TeVCat IDs and Names?

There isn't. One is TeVCat and the other the italian TeGeVCat, no?

**Comment by GernotMaier** [comment]
I've fixed the Crab Nebula.

And yes - there is only one TeVCat name - TeGeVCat and TeVCat is so similar...sorry.

Interesting that the Crab Pulsar is not in TeGeVCat...
