### ISSUE TITLE
Keyword 'data entry status'

### ISSUE THREAD

**Issue by pdeiml** [gammapy/gamma-cat#154]
This is an issue which I assigned to myself:

At the moment we have the problem that we cannot easily say whether gamma-cat is complete or not.

To make this easier, we should add the keyword

data_entry_status = {missing, incomplete, complete}

to all files in /input/data/.

In addition, make.py should get a function that prints a list of all sources and the data_entry_status.

**Comment by cdeil** [comment]
@pdeiml - My suggestion would be to have general discussion on MAGIC in #7, and otherwise create one PR (or issue if useful) per MAGIC paper.

From experience: If you make one issue to discussion several papers like above, the discussion quickly gets very confusing and time-consuming, because it is a linear thread with multiple parallel discussions interspersed.

And concerning the papers you mention: I have no idea and no time to look. Just generally: yes, we're missing almost all MAGIC data.

---

If this issue is just your personal "notepad", then that's fine, I do that often as well to keep track, but then please clearly mention that when posting the issue and assign to yourself. (and I will unsubscribe from the issue notifications, to keep my inbox manageable)

**Comment by cdeil** [comment]
Done by @pdeiml in #155 , continued in #159 .
I'm closing this issue now.

@pdeiml - please check `gamma-cat` master when you're back from vacation, and feel free to open further issues or PRs proposing further improvements.
