### ISSUE TITLE
Move html webpage to docs folder?

### ISSUE THREAD

**Issue by pdeiml** [gammapy/gamma-cat#171]
Currently, all sphinx source code for
http://gamma-cat.readthedocs.io
is located in 
https://github.com/gammapy/gamma-cat/tree/master/documentation
Moreover, the gamma-cat catalog data is located in
https://github.com/gammapy/gamma-cat/tree/master/docs
and @cdeil and me had a discussion about this folder structure.

There are two possibilities:
1) Move html files and catalog data in two separated folders which are located in the same parent toplevel folder
2) Leave it as it is: Two separate folders in the top-level folder 

Moreover, what do you think about renaming the catalog data folder from "docs" to "output" in analogy to the input folder "input"?

**Comment by pdeiml** [comment]
In my opinion, I prefer possibility 1) because in general the documentation website and the collection data has nothing to do with each other and both can "live" without each other. Additionally, it is easier to get familiar with the repository.

I also prefer the renaming of the "docs" folder into "output" or "catalog" or something similar. Firstly because it is more consistent with the terminology of the input folder "input" and secondly, I would think a folder called "docs" has something to do with documentation or with documents and not with a collection of data!

**Comment by cdeil** [comment]
I would suggest to first replicate the functionality of the HTML pages in `docs` in `documentation` (you've already started a PR for this).

When this is done, then the HTML and JS pages in `docs` can be deleted, then
```
git mv docs/data output
```
and then maybe to have a shorter name
```
git mv documentation docs
```

That would leave the data (in `output`) and docs separate. Probably this will not work for the webpage, because it only contains files in `documentation/_build/html`. So as part of the docs build, probably the `output` folder would have to be copied to a sub-folder in `documentation/_build/html` or `documentation/_build/html/static` or something like that.

**Comment by cdeil** [comment]
Done in #195 and #196 . Should be all good now in master.

@pdeiml - Maybe you can have a look? (make sure you don't have any old files lying around, e.g. with `git clean -fdx`, although be aware that this removes all untracked files, i.e. if you have done any edits that weren't committed yet, you should not do this)

**Comment by pdeiml** [comment]
The source list is not being visible on RTD and `make.py webpage` does some weird deletion and copying of folder in the new output path. Don't know when this happened during your big rename PRs.
Nevertheless, I fixed these problems, see
https://github.com/gammapy/gamma-cat/pull/199
