### ISSUE TITLE
Add data for 2016 paper onRXJ1713 by HESS

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#20]
Paper: https://arxiv.org/abs/1609.08671
Flux points (listed at the end of the paper): https://gist.github.com/cdeil/412bf8c648f364e47e71d2cc2651bf5c

**Comment by cdeil** [comment]
@wegenmat - Some more info what to do:

- Add information to `input/sources/tev-000095.yaml` following the pattern from `input/sources/tev-000001.yaml`. Under papers, add `2016arXiv160908671H`.
- Make new directory `input/papers/2016/2016arXiv160908671H` and add files following the example from `input/papers//2006/2006A%26A...457..899A`: `tev-000095.ecsv` and `tev-000095.yaml`

**Comment by wegenmat** [comment]
@cdeil 
- added information from RXJ1713 to `input/sources/tev-000096.yaml`, since this should be the right id refering to https://gammapy.github.io/gamma-cat/sources.html
- commited your suggestions to `input/paper/2016/2016arXiv160908671H/tev-000096.yaml`
- added some descriptions to 'input/schemas/paper_source_info.schema.yaml'

**Comment by cdeil** [comment]
Note to self: I'm fixing the SED now:
https://github.com/gammapy/gamma-cat/blob/master/input/papers/2016/2016arXiv160908671H/tev-000096.ecsv

The paper gives `eflux` and `eflux_err`, and we need to handle this case and compute `dnde` and `dnde_err` from that in `sed.py`.

**Comment by cdeil** [comment]
This dataset should be OK now.

Input files: https://github.com/gammapy/gamma-cat/blob/master/input/papers/2016/2016arXiv160908671H/

Output SED: https://github.com/gammapy/gamma-cat/blob/master/docs/data/sources/000096/gammacat_000096_2016arXiv160908671H_sed.ecsv
