### ISSUE TITLE
Definition of power law with exponential cut off

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gamma-cat#220]
Noticed right  that the definition of the power law with exponential cut off is different than expected. Can you please confirm?

I've expected: dN/dE = I0 · (E/E_ref)−Γ · exp(−E/Ecut)

Looks like the implementation is dN/dE = I0 · (E/E_ref)−Γ · exp(−E*lambda)

If this is true, all ecpl in the VERITAS files need to be adjusted. I will do this, but please confirm that the second implementation is the one used.

**Comment by cdeil** [comment]
@GernotMaier - The difference in the equations you give is just whether they contain `e_cut` or `lambda=1/e_cut`, right?

In gamma-cat we currently use `e_cut`.

You can see this in the schema:
https://github.com/gammapy/gamma-cat/blob/aa4aa0922559b43d602ce06eafeb4ccd222aeb7b/input/schemas/dataset_source_info.schema.yaml#L325
and how the catalog is filled:
https://github.com/gammapy/gamma-cat/blob/ba11b084a1342d64ca80c35a8b46da2f59f20889/gammacat/catalog.py#L325

---

Indeed when we map to a spectral model in Gammapy
https://github.com/gammapy/gammapy/blob/f48b22d7f7ab9430bb2ab78521736a6e381b5318/gammapy/catalog/gammacat.py#L271
we use
http://docs.gammapy.org/dev/api/gammapy.spectrum.models.ExponentialCutoffPowerLaw.html which has `lambda`, but that is filled as `lambda=1/e_cut`.

---

Note that if needed, we can add more spectral models to gamma-cat and Gammapy.
E.g. in Gammapy we already have this second ECPL parametrisation because it was used in the Fermi-LAT 3FGL catalog: http://docs.gammapy.org/dev/api/gammapy.spectrum.models.ExponentialCutoffPowerLaw3FGL.html

---

@GernotMaier - So is there an issue with the data entry for VERITAS?

The HESS catalog will come out soon and I want to add the data to gamma-cat. There we use `lambda` and `lambda_err`. So I guess we should add an ECPL variant to gamma-cat that supports direct data entry of `lambda` and `lambda_err`, no? Any suggestion for what to call it? I think in HESS this is "ecpl3". :-)

**Comment by GernotMaier** [comment]
OK - everything clear. I missed the 1/E_cut and was simply confused - so nothing additional is needed and there is no issue with this. 

(good to be closed).
